//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutris.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Detalhe { get; set; }
        public string loginPaciente { get; set; }
        public string loginNutricionista { get; set; }
    }
}
