//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutris.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutrisEntities : DbContext
    {
        public NutrisEntities()
            : base("name=NutrisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<PlanoAlimentar> PlanoAlimentar { get; set; }
        public DbSet<Receita> Receitas { get; set; }
        public DbSet<ItemPlanoAlimentar> ItemPlanoAlimentar { get; set; }
        public DbSet<PlanoPaciente> PlanoPaciente { get; set; }
    }
}
